pipeline:
  tests:
    image: registry.niklasmh.no/tobot-prod:latest
    when:
      event: push, pull_request
    environment:
      - DOCKER_LOGIN=${DOCKER_LOGIN}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - DOCKER_EMAIL=${DOCKER_EMAIL}
    commands:
      - make drone-container-prod

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    script:
      - make drone-prod
