pipeline:
  deploy:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: root
    port: 22
    when:
      event: push
      branch: development
    commands:
      - cd /home/tobot
      - echo Test >> file.txt
      - echo Testing ...
