pipeline:
  deploy:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    password: ${DEPLOY_PASSWORD}
    port: 22
    when:
      event: push
      branch: development
    script:
      - echo "test" >> file.txt
      - make docker-prod
