pipeline:
  deploy:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    scripts:
      - cd /home/tobot
      - date >> file.txt
      - echo Testing ...
      - make drone-prod
