pipeline:
  ssh:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: pull_request
      branch: development
    script:
      - make drone-image-prod
      - make drone-container-prod

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    script:
      - make drone-prod
