pipeline:
  tests:
    image: registry.niklasmh.no/tobot-prod
    commands:
      - which apt-get
      - which apk
      - make docker-container-prod

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    script:
      - make drone-prod
