pipeline:
  backendend-tests:
    image: registry.niklasmh.no/tobot-baseimage
    when:
      event: push
    commands:
      - echo "${DB_LOGIN}" > java/src/META-INF/db_login.xml
      - echo "${MAIL_LOGIN}" > java/src/META-INF/mail_login.xml
      - echo "${MAIL_PASSWORD}" >> java/src/META-INF/mail_login.xml
      - make backend-build-tests

  frontend-tests:
    image: registry.niklasmh.no/tobot-baseimage
    when:
      event: push
    commands:
      - cd web
      - npm install --depth=0 --quiet
      - npm run build

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    script:
      - cd /home/tobot/tdt4140-bot-project
      - make drone-prod
