pipeline:
  ssh:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: pull_request
      branch: development
    script:
      - cd /home/tobot/tdt4140-bot-project
      - echo ${DRONE_BRANCH}
      - git pull origin ${DRONE_BRANCH}
      - make drone-image-prod
      - make drone-container-prod

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    script:
      - cd /home/tobot
      - date >> file.txt
      - echo Testing ...
      - make drone-prod
