pipeline:
  frontend-tests:
    image: registry.niklasmh.no/tobot-prod
    commands:
      - cd web
      - node --max_semi_space_size=1 --max_old_space_size=198 --max_executable_size=148
      - npm install --silent
      - npm run build

  backendend-tests:
    image: registry.niklasmh.no/tobot-prod
    commands:
      - make backend-build-tests

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    script:
      - make drone-prod
