pipeline:
  frontend-tests:
    image: registry.niklasmh.no/tobot-prod
    commands:
      - cd web
      - ls
      - ls node_modules
      - npm run build

  backendend-tests:
    image: registry.niklasmh.no/tobot-prod
    commands:
      - make backend-build-tests

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    script:
      - make drone-prod
