pipeline:
  frontend-tests:
    image: registry.niklasmh.no/tobot-baseimage
    when:
      event: push
    commands:
      - cd web
      - npm install --depth=0 --quiet
      - npm run build

  backendend-tests:
    image: registry.niklasmh.no/tobot-baseimage
    when:
      event: push
    commands:
      - echo "${DB_LOGIN}" > file.txt
      - cat file.txt
      - make backend-build-tests

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      event: push
      branch: development
    script:
      - cd /home/tobot/tdt4140-bot-project
      - make drone-prod
