pipeline:
  backendend-tests:
    image: registry.niklasmh.no/tobot-baseimage
    when:
      event: pull_request
      branch: development, master
    commands:
      - echo \<?xml version=\"1.0\" encoding=\"UTF-8\"?\> > java/src/META-INF/db_login.xml
      - echo \<property name=\"javax.persistence.jdbc.url\" value=\""${DB_LOGIN}"\"/\> >> java/src/META-INF/db_login.xml
      - echo \<property name=\"javax.persistence.jdbc.user\" value=\""${DB_USERNAME}"\"/\> >> java/src/META-INF/db_login.xml
      - echo \<property name=\"javax.persistence.jdbc.password\" value=\""${DB_PASSWORD}"\"/\> >> java/src/META-INF/db_login.xml
      - echo "${MAIL_LOGIN}" > java/src/META-INF/mail_login.txt
      - echo "${MAIL_PASSWORD}" >> java/src/META-INF/mail_login.txt
      - make backend-build-tests

  frontend-tests:
    image: registry.niklasmh.no/tobot-baseimage
    when:
      event: pull_request
      branch: development, master
    commands:
      - cd web
      - npm install --depth=0 --quiet
      - npm run build

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    port: 22
    when:
      branch: development, master
    script:
      - echo "Release ${DRONE_TAG}"
      - ./deploy.sh "${DRONE_TAG}"

  slack:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: drone
    username: pekka
    icon_url: https://www.idi.ntnu.no/bilder/ansatte/pekkaa.jpg
    template: >
      {{#if build.tag}}
        {{#success build.status}}
          {{uppercasefirst build.tag}} is our new, working release! Pekka is having a nice day. Good job, everyone! {{build.link}}
        {{else}}
          Pekka sad...  Really sad.. Release {{build.tag}} was no success. No release party today. {{build.link}}
        {{/success}}
      {{else}}
        {{#success build.status}}
          Build {{build.number}} succeeded! Pekka is very happy. Good job, {{build.author}}. {{build.link}} ({{build.branch}})
        {{else}}
          Pekka sad... Please fix, {{build.author}}. {{build.link}} ({{build.branch}})
        {{/success}}
      {{/if}}
    when:
      status: [ success, failure ]
