pipeline:
  deploy:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: tobot
    key: ${SSH_KEY}
    port: 22
    when:
      event: push
      branch: development
    script:
      - echo Test >> file.txt
      - echo Testing ...
