# Use this image in production.

FROM tobot/tobot-baseimage

RUN apt-get update

# Move all changes to image
WORKDIR /tobot
COPY . ./

# Install dependencies and build frontend
RUN make frontend-build-prod
RUN npm install babel-plugin-transform-runtime node-libs-browser

# Build backend
RUN make backend-build
EXPOSE 5032

# Run the backend server
CMD [ "make", "backend-run" ]
