# Use this image in production.

FROM tobot/tobot-baseimage

RUN apt-get update

# Move all changes to image
WORKDIR /tobot
COPY . ./

# Install dependencies and build frontend
WORKDIR /tobot/web
RUN make frontend-build-prod

# Build backend
WORKDIR /tobot/java
RUN make backend-build
EXPOSE 5032

# Run the backend server while in /tobot/java
CMD [ "make", "backend-run" ]
