FROM richardkdrew/node-java

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y vim wget curl maven build-essential

# Adding project
RUN mkdir -p /tobot
WORKDIR /tobot
COPY . ./

# Building frontend
RUN make frontend-build-prod

# Building backend
RUN make backend-build
